DROP TABLE IF EXISTS landing_zone CASCADE;


CREATE SCHEMA landing_zone;

CREATE TABLE landing_zone.fire_incidents (
    "Incident Number" text NULL,
    "Exposure Number" int4 NULL,
    "ID" text NULL,
    "Address" text NULL,
    "Incident Date" date NULL,
    "Call Number" text NULL,
    "Alarm DtTm" timestamp NULL,
    "Arrival DtTm" timestamp NULL,
    "Close DtTm" timestamp NULL,
    "City" text NULL,
    zipcode text NULL,
    "Battalion" text NULL,
    "Station Area" text NULL,
    "Box" text NULL,
    "Suppression Units" int4 NULL,
    "Suppression Personnel" int4 NULL,
    "EMS Units" int4 NULL,
    "EMS Personnel" int4 NULL,
    "Other Units" int4 NULL,
    "Other Personnel" int4 NULL,
    "First Unit On Scene" text NULL,
    "Estimated Property Loss" float4 NULL,
    "Estimated Contents Loss" float4 NULL,
    "Fire Fatalities" int4 NULL,
    "Fire Injuries" int4 NULL,
    "Civilian Fatalities" int4 NULL,
    "Civilian Injuries" int4 NULL,
    "Number of Alarms" int4 NULL,
    "Primary Situation" text NULL,
    "Mutual Aid" text NULL,
    "Action Taken Primary" text NULL,
    "Action Taken Secondary" text NULL,
    "Action Taken Other" text NULL,
    "Detector Alerted Occupants" text NULL,
    "Property Use" text NULL,
    "Area of Fire Origin" text NULL,
    "Ignition Cause" text NULL,
    "Ignition Factor Primary" text NULL,
    "Ignition Factor Secondary" text NULL,
    "Heat Source" text NULL,
    "Item First Ignited" text NULL,
    "Human Factors Associated with Ignition" text NULL,
    "Structure Type" text NULL,
    "Structure Status" text NULL,
    "Floor of Fire Origin" int4 NULL,
    "Fire Spread" text NULL,
    "No Flame Spread" text NULL,
    "Number of floors with minimum damage" int4 NULL,
    "Number of floors with significant damage" int4 NULL,
    "Number of floors with heavy damage" int4 NULL,
    "Number of floors with extreme damage" int4 NULL,
    "Detectors Present" text NULL,
    "Detector Type" text NULL,
    "Detector Operation" text NULL,
    "Detector Effectiveness" text NULL,
    "Detector Failure Reason" text NULL,
    "Automatic Extinguishing System Present" text NULL,
    "Automatic Extinguishing Sytem Type" text NULL,
    "Automatic Extinguishing Sytem Perfomance" text NULL,
    "Automatic Extinguishing Sytem Failure Reason" text NULL,
    "Number of Sprinkler Heads Operating" int4 NULL,
    "Supervisor District" text NULL,
    neighborhood_district text NULL,
    point POINT NULL,
    data_as_of timestamp NULL,
    data_loaded_at timestamp NULL
);